site_name: NovaScope
site_url: https://seqscope.github.io/NovaScope

# Repository
repo_name: seqscope/NovaScope
repo_url: https://github.com/seqscope/NovaScope

# Theme configuration
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.indexes
  - navigation.sections
  - content.code.annotate
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/link
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: indigo
    toggle:
      icon: material/toggle-switch-off
      name: Switch to system preference
#    primary: 'deep purple'
#    accent: 'lime'
#  palette:
#    primary: indigo
#    accent: grey
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Navigation structure
nav:
  - Home: 
      - Introduction: index.md
      - Documentation Overview: home/documentation_overview.md
      - Workflow Structure: home/workflow_structure.md
  - Installation:
      - Installing NovaScope: installation/requirement.md
      - Environment Setup: installation/env_setup.md
      - Slurm: installation/slurm.md
  - Getting Started:
      - Introduction: getting_started/intro.md
      - Accessing Input Data: getting_started/access_data.md 
      - Job Configuration : getting_started/job_config.md
      - Executing NovaScope : getting_started/execute.md
      - Output: getting_started/output.md

# Markdown Extensions
markdown_extensions:
  - admonition
#  - codehilite:
#      guess_lang: false 
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      linenums: true
      css_class: 'highlight'
  - pymdownx.superfences
# - pymdownx.inlinehilite


plugins:
  - search
  - open-in-new-tab

# Extra CSS
extra_css:
  - css/custom.css