site_name: NovaScope
site_url: https://seqscope.github.io/NovaScope

# Repository
repo_name: seqscope/NovaScope
repo_url: https://github.com/seqscope/NovaScope

# Theme configuration
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.indexes
  - navigation.sections
#  palette:
#    primary: 'deep purple'
#    accent: 'lime'
  palette:
    primary: indigo
    accent: grey
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Navigation structure
nav:
  - Home: 
      - Introduction: index.md
      - Documentation Overview: home/documentation_overview.md
      - Workflow Structure: home/workflow_structure.md
  - Installation:
      - Requirements: installation/requirement.md
      - Environment Setup: installation/env_setup.md
      - Slurm: installation/slurm.md
  - Getting Started:
      - Preparing Input: getting_started/prep_input.md
      - Executing NovaScope Pipeline: getting_started/execute.md
      - Output: getting_started/output.md

# Markdown Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - attr_list
  - md_in_html

plugins:
  - search
  - open-in-new-tab