site_name: NovaScope
site_url: https://seqscope.github.io/NovaScope

# Repository
repo_name: seqscope/NovaScope
repo_url: https://github.com/seqscope/NovaScope

# Theme configuration
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.indexes
  - navigation.sections
  - content.code.annotate
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/link
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: indigo
    toggle:
      icon: material/toggle-switch-off
      name: Switch to system preference
#    primary: 'deep purple'
#    accent: 'lime'
#  palette:
#    primary: indigo
#    accent: grey
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
#  icon:
#    admonition:
#      <type>: <icon>

# Navigation structure
nav:
  - Home: 
      - Introduction: index.md
      - Documentation Overview: home/documentation_overview.md
      - Workflow Structure: home/workflow_structure.md
  - QuickStart:
      - Introduction: quickstart/intro.md
      - Docker Example: quickstart/docker.md
      - Singularity Example: quickstart/singularity.md
      - Running with Your Own Data: quickstart/custom.md
  - Installation:
      - Installing NovaScope: installation/requirement.md
      - Additional Installations: installation/requirement_for_plus.md
      - Environment Setup: installation/env_setup.md
      - Slurm: installation/slurm.md
  - Basic Usage:
      - Introduction: basic_usage/intro.md
      - Accessing Input Data: basic_usage/access_data.md 
      - Job Configuration : basic_usage/job_config.md
      - Executing NovaScope : basic_usage/execute.md
      - Output: basic_usage/output.md
  - Full Documentation:
      - Introduction: fulldoc/intro.md
      - A Rule Execution Guide: 
        - Core Concepts: fulldoc/execution_guide/core_concepts.md
        - Execution Flow by Request: fulldoc/execution_guide/rule_execution.md
      - Main Rules:
        - fastq2sbcd: fulldoc/rules/fastq2sbcd.md 
        - sbcd2chip : fulldoc/rules/sbcd2chip.md
        - smatch : fulldoc/rules/smatch.md
        - align: fulldoc/rules/align.md
        - dge2sdge: fulldoc/rules/dge2sdge.md
        - sdge_visual: fulldoc/rules/sdge_visual.md
      - Plus Rules:
        - historef: fulldoc/rules/historef.md
        - sdge2sdgeAR: fulldoc/rules/sdge2sdgeAR.md
        - sdgeAR_reformat: fulldoc/rules/sdgeAR_reformat.md
        - sdgeAR_segment: fulldoc/rules/sdgeAR_segment_10x.md

# Markdown Extensions
markdown_extensions:
  - abbr
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
#  - codehilite:
#      guess_lang: false 
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      linenums: true
      css_class: 'highlight'
  - pymdownx.superfences
# - pymdownx.inlinehilite


plugins:
  - search
  - open-in-new-tab

# Extra CSS
extra_css:
  - css/custom.css