
cluster:
  mkdir -p logs/{rule}/ &&
  sbatch
    --job-name={rule}_{wildcards}
    --output=logs/{rule}/{rule}___{wildcards}___%j.out
    --error=logs/{rule}/{rule}___{wildcards}___%j.err
    --account={resources.account}
    --partition={resources.partition}
    --mem={resources.mem}
    --time={resources.time}
    --cpus-per-task={threads}
    --parsable
    --nodes={resources.nodes}

default-resources:
  - partition="standard"
  - mem="6500MB"
  - time="05:00:00"
  - nodes=1
  - account="leeju0" 

jobs: 9                        
latency-wait: 120              
local-cores: 20                
restart-times: 0               
max-jobs-per-second: 20
keep-going: True
rerun-incomplete: True
printshellcmds: True

use-conda: True
conda-frontend: conda
