## ================================================
##
## Mandatory fields:
##
## ================================================

# Input
input:
  flowcell: N3-HG5MC
  section: B08Ctest
  specie: "mouse"
  lane: 3                 ## Specifies the lane used. Auto-assigned based on section's last letter if missing (A->1, B->2, C->3, D->4).
  seq1st:
    prefix: L3_filt       ## Defaults to "L{lane}".
    fastq: "input_data/seq1st/fastqs/9203-AP.L3.2456_2556.R1_001.fastq.gz"
    sbcd_layout: "input_data/seq1st/layout/B08Csub.layout.tsv" ## ## Provide sbcd_layout_summary or sbcd_layout.
  seq2nd:
    - prefix: B08Cv1.filt
      fastq_R1: "input_data/seq2nd/fastqs/B08Cv1.filt/B08Cv1.filt.R1.fastq.gz"
      fastq_R2: "input_data/seq2nd/fastqs/B08Cv1.filt/B08Cv1.filt.R2.fastq.gz"
  label: "v1"              ## Version label for the input seq2 data, if applicable.

# Output
output: "/nfs/turbo/umms-leeju/v5"

request:
  - nbcd-per-section
  - nmatch-per-section
  - align-per-section
  - nge-per-section

# Environment
env: /nfs/turbo/sph-hmkang/index/data/weiqiuc/NovaScope_local/env ## If absent, the pipeline will check if a "env" directory exists in the Novascope directory.

execution: "HPC"   ## Options: HPC and Local.


## ================================================
##
##  Optional fields:
##    Enable the following parameters only if you wish to utilize values different than the default.
##
## ================================================

preprocess:
  fastq2sbcd:
    format: DraI31        ## Default: "DraI32".
#  sbcd2nbcd:
#    gap_row: 0.0517
#    gap_col: 0.0048
#    dup_maxnum: 1
#    dup_maxdist: 0.1
  nmatch:
    skip_sbcd: 0
#    match_len: 27
#  align:
#    len_sbcd: 30
#    min_match_len: 30
#    min_match_frac: 0.66
#    resource:
#      assign_type: stdin    ## Options: filesize, stdin. If filesize, no need to specify the three value below.
#      partition: standard
#      threads: 10
#      memory: 70000m
#  gene_visual: None         ## Specify the file name containing a list of gene names (one per line) here if you have a specific set of genes to visualize. By default, the top five genes with the highest expression are visualized.
#  visualization:
#    drawxy:
#      coord_per_pixel: 1000
#      intensity_per_obs: 50
#      icol_x: 3
#      icol_y: 4
