## See more details for each parameter at https://github.com/seqscope/NovaScope/blob/main/docs/prep_input.md

input:
  flowcell: N3-HG5MC
  section: B08Ctest
  specie: "mouse"
  lane: 3
  seq1st:
    prefix: L3_filt
    fastq: "input_data/seq1st/fastqs/9203-AP.L3.2456_2556.R1_001.fastq.gz"
    layout: "input_data/seq1st/layout/B08Csub.layout.tsv"
  seq2nd:
    - prefix: B08Cv1.filt
      fastq_R1: "input_data/seq2nd/fastqs/B08Cv1.filt/B08Cv1.filt.R1.fastq.gz"
      fastq_R2: "input_data/seq2nd/fastqs/B08Cv1.filt/B08Cv1.filt.R2.fastq.gz"
  label: "v1"

output: "/nfs/turbo/umms-leeju/v5"

request:
  - sbcd-per-flowcell
  - sbcd-per-section
  - smatch-per-section
  - align-per-section
  - sge-per-section

env_yml: /nfs/turbo/sph-hmkang/index/data/weiqiuc/NovaScope/info/config_env.yaml

preprocess:
  fastq2sbcd:
    format: DraI31
  smatch:
    skip_sbcd: 0
