input:
  flowcell: N3-HG5MC
  section: B08Ctest
  specie: "mouse"
  lane: 3                 # Specifies the lane used. Auto-assigned based on section's last letter if missing (A->1, B->2, C->3, D->4).
  seq1st:
    prefix: L3_filt       # Defaults to "L{lane}" if absent.
    fastq: "input_data/seq1st/fastqs/9203-AP.L3.2456_2556.R1_001.fastq.gz"
    sbcd_layout: "input_data/seq1st/layout/B08Csub.layout.tsv" # Tile layout for the section. Defaults to generating from sbcd_layout_summary if absent.
  seq2nd:
    - prefix: B08Cv1.filt
      fastq_R1: "input_data/seq2nd/fastqs/B08Cv1.filt/B08Cv1.filt.R1.fastq.gz"
      fastq_R2: "input_data/seq2nd/fastqs/B08Cv1.filt/B08Cv1.filt.R2.fastq.gz"
  label: "v1"              # Version label for the input seq2 data, if applicable.

output: "/nfs/turbo/umms-leeju/v5"

preprocess:
  fastq2sbcd:
    format: DraI31        #Default value is "DraI32".

env: /nfs/turbo/sph-hmkang/index/data/weiqiuc/env_test
