## Path to the dependent software tools
## Please replace /path/to the actual path to the binary of the software tools
tools:
  spatula: "/path/to/spatula/bin/spatula"
  samtools: "/path/to/samtools/samtools"
  star: "/path/to/STAR_2_7_11b/bin/Linux_x86_64_static/STAR"

# module-specific configuration:
# If your system supports module loading, you may specify the module names for the required software tools.
envmodules:
  python: "python/3.9.12"
  gcc: "gcc/10.3.0"
  gdal: "gdal/3.5.1"
  imagemagick: "imagemagick/7.1.0-25.lua"

## Path to the reference genomes
## For each species, you need to provide the path to the STAR index
ref:
  align:
    mouse: "/path/to/refdata-gex-GRCm39-2024-A/star"
    human: "/path/to/refdata-gex-GRCh39-2024-A/star"
## you may add other reference data here

## Path to the python virtual environment
pyenv: "/path/to/python/virtual/env"
