## See more details for each parameter at https://github.com/seqscope/NovaScope/blob/main/docs/getting_started/job_config.md
## IMPORTANT TODO: DOWNLOAD THE SHALLOW INPUT DATA from https://doi.org/10.5281/zenodo.10835761
##                 DOWNLOAD ADDITIONAL FASTQ FILES from http://deepblue.lib.umich.edu/data/concern/data_sets/2227mq44w
## IMPORTANT TODO: REPLACE THE FOLLOWING VARIABLES BEFORE USE
## /path/to/input/dir  to the absolute path of the input data
## /path/to/output/dir to the absolute path of the output directory
## /path/to/config_env.yaml to the absolute path of the config_env.yaml file (e.g. NovaScope/info/config_env.yaml)


## See more details for each parameter at https://github.com/seqscope/NovaScope/blob/main/docs/prep_input.md

input:
  flowcell: N3-HG5MC
  chip: B08C
  species: "mouse"
  seq1st:
    prefix: null
    ## IMPORTANT: REPLACE THE FOLLOWING VARIABLE BEFORE USE
    fastq: "/path/to/input/dir/9203-AP.L3.B08C.R1_001.fastq.gz"
  seq2nd: 
    ## IMPORTANT: REPLACE ALL OF THE FOLLOWING VARIABLES BEFORE USE
    - prefix: N3_B08C_v1
      fastq_R1: "/path/to/input/dir/9748-YK-3_CGAGGCTG_S3_R1_001.fastq.gz"
      fastq_R2: "/path/to/input/dir/9748-YK-3_CGAGGCTG_S3_R2_001.fastq.gz"
    - prefix: N3_B08C_v2a
      fastq_R1: "/path/to/input/dir/seq2nd/fastqs/B08Cv2a/B08Cv2a.R1.fastq.gz"
      fastq_R1: "/path/to/input/dir/seq2nd/fastqs/B08Cv2a/B08Cv2a.R2.fastq.gz"
    - prefix: N3_B08C_v2b
      fastq_R1: "/path/to/input/dir/seq2nd/fastqs/B08Cv2b/B08Cv2b.R1.fastq.gz"
      fastq_R1: "/path/to/input/dir/seq2nd/fastqs/B08Cv2b/B08Cv2b.R2.fastq.gz"
    - prefix: N3_B08C_v2bu
      fastq_R1: "/path/to/input/dir/seq2nd/fastqs/B08Cv2bu/B08Cv2bu.R1.fastq.gz"
      fastq_R1: "/path/to/input/dir/seq2nd/fastqs/B08Cv2bu/B08Cv2bu.R2.fastq.gz"
    - prefix: N3_B08C_v2c
      fastq_R1: "/path/to/input/dir/seq2nd/fastqs/B08Cv2c/B08Cv2c.R1.fastq.gz"
      fastq_R1: "/path/to/input/dir/seq2nd/fastqs/B08Cv2c/B08Cv2c.R2.fastq.gz"
    - prefix: N3_B08C_v2cu
      fastq_R1: "/path/to/input/dir/seq2nd/fastqs/B08Cv2cu/B08Cv2cu.R1.fastq.gz"
      fastq_R1: "/path/to/input/dir/seq2nd/fastqs/B08Cv2cu/B08Cv2cu.R2.fastq.gz"
    - prefix: N3_B08C_v3a
      fastq_R1: "/path/to/input/dir/seq2nd/fastqs/B08Cv3a/B08Cv3a.R1.fastq.gz"
      fastq_R1: "/path/to/input/dir/seq2nd/fastqs/B08Cv3a/B08Cv3a.R2.fastq.gz"
    - prefix: N3_B08C_v3b
      fastq_R1: "/path/to/input/dir/seq2nd/fastqs/B08Cv3b/B08Cv3b.R1.fastq.gz"
      fastq_R1: "/path/to/input/dir/seq2nd/fastqs/B08Cv3b/B08Cv3b.R2.fastq.gz"
  label: v123
  ## IMPORTANT: REPLACE THE FOLLOWING VARIABLE BEFORE USE
  histology: "/path/to/input/dir/histology.tif"

## IMPORTANT: REPLACE THE FOLLOWING VARIABLE BEFORE USE
output: "/path/to/output/dir"

request:
  - sge-per-chip
  - hist-per-chip

## IMPORTANT: REPLACE/MODIFY THE FOLLOWING VARIABLE BEFORE USE
## It is important to configure the environment file for your specific environment.
env_yml: /path/to/config_env.yaml

preprocess:
  fastq2sbcd:
    format: DraI31